#ifndef __USB_KEYLOG_H__
#define __USB_KEYLOG_H__

int const key_codes[] = { KEY_TILDE,
						  KEY_1,
					      KEY_2,
						  KEY_3,
						  KEY_4,
						  KEY_5,
						  KEY_6,
					      KEY_7,
					      KEY_8,
					      KEY_9,
					      KEY_0,
				 	      KEY_MINUS,
					      KEY_EQUAL,
					      KEY_Q,
					      KEY_W,
					      KEY_E,
					      KEY_R,
					      KEY_T,
					      KEY_Y,
					      KEY_U,
					      KEY_I,
					      KEY_O,
					      KEY_P,
					      KEY_LEFT_BRACE,
					      KEY_RIGHT_BRACE,
					      KEY_BACKSLASH,
					      KEY_A,
					      KEY_S,
					      KEY_D,
					      KEY_F,
					      KEY_G,
					      KEY_H,
					      KEY_J,
					      KEY_K,
					      KEY_L,
					      KEY_SEMICOLON,
					      KEY_QUOTE,
					      KEY_Z,
					      KEY_X,
					      KEY_C,
					      KEY_V,
					      KEY_B,
					      KEY_M,
					      KEY_N,
					      KEY_COMMA,
					      KEY_PERIOD,
					      KEY_SLASH };  //48

const int KEY_CODE_ARRAY_LEN = 48;

char* const key_char[] = { "`",			
						   "1",
					       "2",
						   "3",
						   "4",
						   "5",
						   "6",
					       "7",
					       "8",
					       "9",
					       "0",
				 	       "-",
					       "=",
					       "Q",
					       "W",
					       "E",
					       "R",
					       "T",
					       "Y",
					       "U",
					       "I",
					       "O",
					       "P",
					       "[",
					       "]",
					       "\\",
					       "A",
					       "S",
					       "D",
					       "F",
					       "G",
					       "H",
					       "J",
					       "K",
					       "L",
					       ";",
					       "'",
					       "Z",
					       "X",
					       "C",
					       "V",
					       "B",
					       "M",
					       "N",
					       ",",
					       ".",
						   "/" };

int const key_codes_alpha[] = { KEY_Q,
					      KEY_W,
					      KEY_E,
					      KEY_R,
					      KEY_T,
					      KEY_Y,
					      KEY_U,
					      KEY_I,
					      KEY_O,
					      KEY_P,
					      KEY_A,
					      KEY_S,
					      KEY_D,
					      KEY_F,
					      KEY_G,
					      KEY_H,
					      KEY_J,
					      KEY_K,
					      KEY_L,
					      KEY_Z,
					      KEY_X,
					      KEY_C,
					      KEY_V,
					      KEY_B,
					      KEY_M,
					      KEY_N};  //26

const int KEY_CODE_ARRAY_ALPHA_LEN = 26;

char* const key_char_alpha[] = { "Q",
					       "W",
					       "E",
					       "R",
					       "T",
					       "Y",
					       "U",
					       "I",
					       "O",
					       "P",
					       "A",
					       "S",
					       "D",
					       "F",
					       "G",
					       "H",
					       "J",
					       "K",
					       "L",
					       "Z",
					       "X",
					       "C",
					       "V",
					       "B",
					       "M",
					       "N"};
						  
int crack_code_0[sizeof(key_codes_alpha)];
int crack_code_1[sizeof(key_codes_alpha)];
int crack_code_2[sizeof(key_codes_alpha)];

						  
#endif						  
						  
						  
						  
						  